#define HTTPD_SERVER_PORT 80
#define HTTPD_FSDATA_FILE "fsdata.inc"
#define LWIP_HTTPD_SUPPORT_REQUESTLIST 1
#define LWIP_HTTPD_SUPPORT_POST 1
#define HTTPD_DEBUG LWIP_DBG_OFF
#define LWIP_DEBUG LWIP_DBG_ON

